os: linux
language: java
jdk: openjdk8

jobs:
  include:
    - stage: unit-test
      name: Unit Tests
      script: "./gradlew test"

    - stage: compat-tests
      script: "./gradlew compatTest4.9"
      name: "Compat tests for Gradle 4.9"
    - script: "./gradlew compatTest4.10.3"
      name: "Compat tests for Gradle 4.10.3 "
    - script: "./gradlew compatTest5.1.1"
      name: "Compat tests for Gradle 5.1.1"
    - script: "./gradlew compatTest5.6.4"
      name: "Compat tests for Gradle 5.6.4"
    - script: "./gradlew compatTest6.0.1"
      name: "Compat tests for Gradle 6.0.1"
    - script: "./gradlew compatTest6.8.3"
      name: "Compat tests for Gradle 6.8.3"
    - script: "./gradlew compatTest7.0"
      name: "Compat tests for Gradle 7.0"

    - stage: release
      script: skip
      deploy:
        - provider: script
          script: ./gradlew publish publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
          on:
            tags: true
        - provider: releases
          token: $GITHUB_KEY
          file_glob: true
          file: build/libs/*.jar
          on:
            tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
