name: master
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Run unit tests
        run: ./gradlew test
  compat_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle_version:
          - "4.9"
          - "4.10.3"
          - "5.1.1"
          - "5.6.4"
          - "6.0.1"
          - "6.9.1"
          - "7.0.2"
          - "7.3.1"
    steps:
      - name: Download repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Run compat tests for Gradle ${{ matrix.gradle_version }}
        run: ./gradlew compatTest${{ matrix.gradle_version }}
