name: master
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Run unit tests
        run: ./gradlew test
  compat_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version:
          - "8"
          - "11"
    steps:
      - name: Download repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Run Gradle compat tests for Java ${{ matrix.java_version }}
        run: ./gradlew compatTestJava${{ matrix.java_version }}
