name: Release
on:
  push:
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - name: Configure Gradle
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          mkdir -p $HOME/.gradle/ &&
          echo gradle.publish.key=$GRADLE_PUBLISH_KEY >> $HOME/.gradle/gradle.properties &&
          echo gradle.publish.secret=$GRADLE_PUBLISH_SECRET >> $HOME/.gradle/gradle.properties
      - name: Publish to GitHub Packages and Gradle Plugins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish publishPlugins
